name: Create config.json

on:
  push:
    branches:
      - main
      - develop
      - staging
      - qa

jobs:
  create-config:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set environment name
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "ENV_NAME=tkxelprod" >> $GITHUB_ENV
        elif [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then
          echo "ENV_NAME=tkxeldev" >> $GITHUB_ENV
        elif [[ ${{ github.ref }} == 'refs/heads/staging' ]]; then
          echo "ENV_NAME=tkxelstaging" >> $GITHUB_ENV
        elif [[ ${{ github.ref }} == 'refs/heads/qa' ]]; then
          echo "ENV_NAME=tkxelqa" >> $GITHUB_ENV
        else
          echo "ENV_NAME=tkxelunknown" >> $GITHUB_ENV
        fi

    - name: Create config.json
      env:
        PROD_HOST_NAME: ${{ secrets.PROD_HOST_NAME }}
        PROD_MAP_LICENSE: ${{ secrets.PROD_MAP_LICENSE }}
        PROD_MAP_KEY: ${{ secrets.PROD_MAP_KEY }}
        PROD_BASE_URL: ${{ secrets.PROD_BASE_URL }}
        DEV_HOST_NAME: ${{ secrets.DEV_HOST_NAME }}
        DEV_MAP_LICENSE: ${{ secrets.DEV_MAP_LICENSE }}
        DEV_MAP_KEY: ${{ secrets.DEV_MAP_KEY }}
        DEV_BASE_URL: ${{ secrets.DEV_BASE_URL }}
        STAGING_HOST_NAME: ${{ secrets.STAGING_HOST_NAME }}
        STAGING_MAP_LICENSE: ${{ secrets.STAGING_MAP_LICENSE }}
        STAGING_MAP_KEY: ${{ secrets.STAGING_MAP_KEY }}
        STAGING_BASE_URL: ${{ secrets.STAGING_BASE_URL }}
        QA_HOST_NAME: ${{ secrets.QA_HOST_NAME }}
        QA_MAP_LICENSE: ${{ secrets.QA_MAP_LICENSE }}
        QA_MAP_KEY: ${{ secrets.QA_MAP_KEY }}
        QA_BASE_URL: ${{ secrets.QA_BASE_URL }}
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          HOST_NAME=$PROD_HOST_NAME
          MAP_LICENSE=$PROD_MAP_LICENSE
          MAP_KEY=$PROD_MAP_KEY
          BASE_URL=$PROD_BASE_URL
        elif [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then
          HOST_NAME=$DEV_HOST_NAME
          MAP_LICENSE=$DEV_MAP_LICENSE
          MAP_KEY=$DEV_MAP_KEY
          BASE_URL=$DEV_BASE_URL
        elif [[ ${{ github.ref }} == 'refs/heads/staging' ]]; then
          HOST_NAME=$STAGING_HOST_NAME
          MAP_LICENSE=$STAGING_MAP_LICENSE
          MAP_KEY=$STAGING_MAP_KEY
          BASE_URL=$STAGING_BASE_URL
        elif [[ ${{ github.ref }} == 'refs/heads/qa' ]]; then
          HOST_NAME=$QA_HOST_NAME
          MAP_LICENSE=$QA_MAP_LICENSE
          MAP_KEY=$QA_MAP_KEY
          BASE_URL=$QA_BASE_URL
        else
          echo "Unknown branch"
          exit 1
        fi

        cat << EOF > config.json
        {
          "$ENV_NAME": {
            "host_name": "$HOST_NAME",
            "map_license": "$MAP_LICENSE",
            "map_key": "$MAP_KEY",
            "base_url": "$BASE_URL"
          }
        }
        EOF

    - name: Display config.json content
      run: cat config.json