name: Create config.json

on:
  push:
    branches:
      - main
      - develop
      - staging

jobs:
  create-config:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set environment based on branch
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "ENVIRONMENT=production" >> $GITHUB_ENV
        elif [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then
          echo "ENVIRONMENT=development" >> $GITHUB_ENV
        elif [[ ${{ github.ref }} == 'refs/heads/staging' ]]; then
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
        else
          echo "ENVIRONMENT=unknown" >> $GITHUB_ENV
        fi

    - name: Create config.json
      env:
        PROD_HOST_NAME: ${{ secrets.PROD_HOST_NAME }}
        PROD_MAP_LICENSE: ${{ secrets.PROD_MAP_LICENSE }}
        PROD_MAP_KEY: ${{ secrets.PROD_MAP_KEY }}
        PROD_BASE_URL: ${{ secrets.PROD_BASE_URL }}
        DEV_HOST_NAME: ${{ secrets.DEV_HOST_NAME }}
        DEV_MAP_LICENSE: ${{ secrets.DEV_MAP_LICENSE }}
        DEV_MAP_KEY: ${{ secrets.DEV_MAP_KEY }}
        DEV_BASE_URL: ${{ secrets.DEV_BASE_URL }}
        STAGING_HOST_NAME: ${{ secrets.STAGING_HOST_NAME }}
        STAGING_MAP_LICENSE: ${{ secrets.STAGING_MAP_LICENSE }}
        STAGING_MAP_KEY: ${{ secrets.STAGING_MAP_KEY }}
        STAGING_BASE_URL: ${{ secrets.STAGING_BASE_URL }}
      run: |
        if [[ $ENVIRONMENT == 'production' ]]; then
          HOST_NAME=$PROD_HOST_NAME
          MAP_LICENSE=$PROD_MAP_LICENSE
          MAP_KEY=$PROD_MAP_KEY
          BASE_URL=$PROD_BASE_URL
        elif [[ $ENVIRONMENT == 'development' ]]; then
          HOST_NAME=$DEV_HOST_NAME
          MAP_LICENSE=$DEV_MAP_LICENSE
          MAP_KEY=$DEV_MAP_KEY
          BASE_URL=$DEV_BASE_URL
        elif [[ $ENVIRONMENT == 'staging' ]]; then
          HOST_NAME=$STAGING_HOST_NAME
          MAP_LICENSE=$STAGING_MAP_LICENSE
          MAP_KEY=$STAGING_MAP_KEY
          BASE_URL=$STAGING_BASE_URL
        else
          echo "Unknown environment"
          exit 1
        fi

        cat << EOF > config.json
        {
          "tkxeldev": {
            "host_name": "$HOST_NAME",
            "map_license": "$MAP_LICENSE",
            "map_key": "$MAP_KEY",
            "base_url": "$BASE_URL"
          }
        }
        EOF

    - name: Display config.json content
      run: cat config.json
      #lovedevops